apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypostgrespersistentvolumeclaim
  labels:
    type: local
spec:
  selector:
    matchLabels:
      type: local
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 6Gi

  # persistentVolumeReclaimPolicy: Retain
  # hostPath:
  #   path: /volumes/mypostgres
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
