apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myrancherpersistentvolumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 6Gi

  # persistentVolumeReclaimPolicy: Retain
  # hostPath:
  #   path: /volumes/mypostgres
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
