apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypostgrespersistentvolume
  labels:
    type: local
spec:
  storageClassName: local-path 
  capacity:
    storage: 10Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /volumes/mypostgres
  # storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
